// Scans public/media/{photos,music} and writes public/media.js, the list the site reads.
// Add or remove files in those folders, then run:  npm run media
// Files are shown/played in name order, so prefix them with numbers (01-, 02-, ...).
import fs from 'node:fs/promises';

const KINDS = { jpg: 'image', jpeg: 'image', png: 'image', webp: 'image', gif: 'image',
  mp4: 'video', mov: 'video', webm: 'video', m4v: 'video', mp3: 'audio', m4a: 'audio', wav: 'audio', ogg: 'audio' };

const items = [];
for (const dir of ['photos', 'music']) {
  const names = (await fs.readdir(`public/media/${dir}`).catch(() => [])).filter((n) => !n.startsWith('.')).sort();
  for (const name of names) {
    const kind = KINDS[name.split('.').pop().toLowerCase()];
    if (kind) items.push({ url: `media/${dir}/${name}`, kind });
  }
}
const js = `// Generated by scripts/build-media.mjs — run \`npm run media\` after changing public/media.\nwindow.MEDIA = ${JSON.stringify(items, null, 2)};\n`;
await fs.writeFile('public/media.js', js);
console.log(`public/media.js: ${items.filter((i) => i.kind !== 'audio').length} photos/videos, ${items.filter((i) => i.kind === 'audio').length} songs`);
